# Generated by Django 2.2.7 on 2019-11-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='Type',
            new_name='Tag',
        ),
        migrations.AddField(
            model_name='file',
            name='upload',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
