# Generated by Django 2.2.7 on 2019-11-26 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20191127_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='DateCreated',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='Tag',
            new_name='tag',
        ),
    ]
