# Generated by Django 2.2.7 on 2019-11-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_auto_20191127_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Select a tag for this file', to='www.Tag'),
        ),
    ]
