# Generated by Django 2.2.7 on 2019-11-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_auto_20191127_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='course',
            field=models.ManyToManyField(blank=True, help_text='Select a course for this file', to='www.Course'),
        ),
    ]
