# Generated by Django 2.2.7 on 2019-11-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0006_auto_20191127_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
