# Generated by Django 2.2.7 on 2019-12-03 15:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_auto_20191128_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='courseid', unique=True),
        ),
        migrations.AddField(
            model_name='file',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='tag', unique=True),
        ),
    ]
